Revert "Fix issue 189 (#197)"
This reverts commit 579fc8763f10ed6048773f923891d79d7e0568d4.

Reason: go-vet fails:

```
Error: ./syscall_cgo_linux.go:14:33: undefined: cgo.Syscall9XABI0
Error: ./syscall_cgo_linux.go:25:13: undefined: cgo.Syscall9X
Error: Process completed with exit code 1.
```