Revert "purego: fix float returns (#177)"
This reverts commit 2a2fe0f2bfbd84fa932e6af44c559f74eec9b600.

Reason: test failures on Ubuntu:

```
=== RUN   TestRegisterFunc_Floats
    func_test.go:119: strtof failed. got 0.000000 but wanted 2.000000
    func_test.go:131: strtod failed. got 0.000000 but wanted 1.000000
--- FAIL: TestRegisterFunc_Floats (0.00s)
```